#!/usr/bin/perl -w
use strict;
use warnings;

my $EXITCODE = 0;

#from getopts.perl
use Getopt::Std;
my %OPTS;
getopts("d", \%OPTS);

#from sigtoperl.output
my %strsignal = (
    1 => "Hangup",
    2 => "Interrupt",
    3 => "Quit",
    4 => "Illegal instruction",
    5 => "Trace/breakpoint trap",
    6 => "Aborted",
    7 => "Bus error",
    8 => "Floating point exception",
    9 => "Killed",
   11 => "Segmentation fault",
   13 => "Broken pipe",
   14 => "Alarm clock",
   15 => "Terminated",
   16 => "Stack fault",
   17 => "Child exited",
   18 => "Continued",
   19 => "Stopped (signal)",
   20 => "Stopped",
   21 => "Stopped (tty input)",
   22 => "Stopped (tty output)",
   24 => "CPU time limit exceeded",
   25 => "File size limit exceeded",
   26 => "Virtual timer expired",
   27 => "Profiling timer expired",
   28 => "Window changed",
   29 => "I/O possible",
   30 => "Power failure",
   31 => "Bad system call",
);

# init filename if theres no file then filename will be set to Makefile
my $filename = "Makefile";
my $target = exists $ARGV[0] ? $ARGV[0] : undef;

# debugging information
print "filename: $filename\n" if $OPTS{'d'};
print "global target: $target\n" if $OPTS{'d'};


my %macrohash;
my %dephash;
my %cmdhash;

#
my %dephashnonsplit;
my %cmdhashstringed;

my %istargetcomplete;
my @alltargets;
my $somethingdone = 0;

sub fetchhash {
    my $key = $_[0];
    #print "fetch hash $key\n";
    #print "its $macrohash{$key}\n" if exists $macrohash{$key};
    #return "hi";
    if (exists $macrohash{$key}) {
        return $macrohash{$key};
    }
    elsif ($key =~ m/\$\$/) {
        return '$';
    }
    # first file spec. as a prereq
    elsif ($key =~ m/\$</) {
        my @deps = $dephash{$target};
        return $deps[0];
    }
    #first file spec. as a target.
    elsif ($key =~ m/\@/) {
        foreach my $tar (@alltargets) {
            if (-e $tar) {
                return $tar;
            }
        }
    }
    else {
      #Time to do nexted macros!
      return $key;
    };
};

sub macrosub {
    my $line = $_[0];
    #print "pre  $line\n";
    $line =~ s/\${(\S*)}/fetchhash($1)/eg;
    #print "mid  $line\n";
    $line =~ s/(\$\$)/fetchhash($1)/eg;
    #print "post $line\n";
    #$line =~ s/(\$<)/fetchhash($1)/eg;
    return $line;
}

#fn for adding line to hashtable
sub inithash {
    my $line = $_[0];
    my ($key, $val) = split(/\s*=\s*/, $line);
    print "key: $key val: $val\n" if $OPTS{'d'};
    #print"val: $val\n";
    $val = macrosub $val;
    #print"next: $val\n";
    $macrohash{$key} = $val;
};


sub executecmd {
    my $line = $_[0];
    if (defined $line) {
        $line =~ s/\t//;
        $line = macrosub $line;
        #print "$line\n";
        #print "cmd: $line\n";
        print "$line\n";
        # @ cmd
        if ($line =~ m/\s*@\s+(.+)/) {
            $line =~ s/@ //;
        }
        # - cmd
        elsif ($line =~ m/^\s*-\s+(.+)/gm) {
            $line =~ s/- //;
        }
        else {
            print "$line\n";
        }
        system("$line");
        my $term_signal = $? & 0x7F;
        my $core_dumped = $? & 0x80;
        my $exit_status = ($? >> 8) & 0xFF;
        #print "term signal $term_signal\n";
        #print "core dumped $core_dumped\n";
        #print "exit status  $exit_status\n";
    }
}

# from cat.perl
open my $infile, "<$filename" or warn "<$filename: $!\n" and next;

my $currtarget;
my @cmds = ();
while (defined (my $line = <$infile>)) {
    chomp $line;
    # (m) is the match operator || capture groups
    # makefile syntax if # (comment) ignore
    next if $line =~ m/^\s*#/;
    # if macro = value -> put into hashtable (\S+) is the regex pattern to get macro val
    if ($line =~ m/\s*(\S+)\s*=\s+(.+)/ && $line !~ /\t\s*.+/) {
        #print "macro detected: $line\n" if $OPTS{'d'};
        inithash $line;
        #my $key, $value = split '=' $line;
        #my ($key, $val) = split(/\s*=\s*/, $line);
        #print "key: $key val: $val\n";
    }
    # target ... : prereq
    elsif ($line =~ m/^(\S+)\s*:.*/mg) {
        #print "target prereq detected: $line\n" if $OPTS{'d'};
        my $depstring;
        ($currtarget, $depstring) = split(/\s*(:\s.*)/, $line);
        $depstring = "" if (not defined $depstring);

        #this regex replaces all macros
        $depstring = macrosub $depstring;
        $currtarget = macrosub $currtarget;


        my @deps = split / /, $depstring;
        #these 2 lines clean up the deps and target
        shift @deps;
        $currtarget =~ s/ ://;
        @cmds = ();

        push @alltargets, $currtarget;
        $dephashnonsplit{$currtarget} = $depstring;

        $istargetcomplete{$currtarget} = 0;
        #print "target: $currtarget  deps: @deps  cmds: @cmds\n" ;
        $dephash{$currtarget} = [@deps];
    }
    # command (\t)
    elsif ($line =~ m/\t\s*(.+)/) {
        $line = macrosub $line;
        push @cmds, $line;
        
        $cmdhash{$currtarget} = [@cmds];
        $cmdhashstringed{$currtarget} = $line;
    }
}


sub handlewildcard {
    my $dep = $_[0];
    my $regextar;
    my $tar = "";
    my $exists = 0;
    #print "$dep\n";
    foreach my $k (keys %dephash) {
        if ($k =~ m/%(.+)/) {
            $tar = $1;
            $exists = 1;
        }
    }
    if (!defined $dephash{$dep}) {
        foreach my $macro (keys %macrohash) {
            my $macroval = $macrohash{$macro};
            my @macrovalarr = split / /, $macroval;
            foreach my $val (@macrovalarr) {
                $regextar = "\\" . $tar;
                if ($val =~ m/.+($regextar)/) {
                    my $getwildcard = "%" . $tar;
                    #print "$getwildcard\n";
                    my @wildcardpreq = @{$dephash{$getwildcard}};
                    #print "@wildcardpreq\n";
                    my @getwccmds = @{$cmdhash{$getwildcard}};
                    my $tarname = $val;
                    if ($tarname =~ m/(\S+)\./) {
                        $tarname = $1;
                    }
                    my $newtar = $tarname . $tar;
                    push @alltargets, $newtar;
                    $wildcardpreq[0] =~ s/^.//;
                    my $newpreq = $tarname . $wildcardpreq[0];
                    #print "$newpreq\n";

                    foreach my $cmd (@getwccmds) {
                        $cmd =~ s/\$\</$newpreq/;
                    }
                    $dephashnonsplit{$newtar} = $newpreq;
                    $cmdhash{$newtar} = [@getwccmds];
                    #print "@{$cmdhash{$newtar}}\n";
                    $cmdhashstringed{$newtar} = join ' ', @getwccmds;
                }
            }
        }
    }
    elsif ($exists) {
        # make the hashtable
        #rint "$dep\n";
        $regextar = "\\" . $tar;
        #print "$tar\n";
        if ($dep =~ m/.+($regextar)/) {
            my $getwildcard = "%" . $tar;
            #print "$getwildcard\n";
            my @wildcardcmdarr = @{$cmdhash{$getwildcard}};
            my @getwildcarddeps = @{$dephash{$getwildcard}};
            
            #print "@getwildcarddeps\n";
            #print "$getwildcarddeps\n";
            #print "$dep\n";

            $getwildcarddeps[0] =~ s/^.//;
            #print "$getwildcarddeps[0]\n";
            my @currdeps;

            if (defined $dephash{$dep}) {
                @currdeps = @{$dephash{$dep}};
            }
            my $depprereq = "";

            foreach my $thisdep (@currdeps) {
                if ($thisdep =~ m/.+($getwildcarddeps[0])/) {
                    $depprereq = $thisdep;
                }
            }
            foreach my $str (@wildcardcmdarr) {
                $str =~ s/\$\</$depprereq/;
            }
            #print "$depprereq\n";
            my $newstring = join ' ', @wildcardcmdarr;
            #print "$newstring\n";
            $dephashnonsplit{$dep} = $depprereq;
            $cmdhashstringed{$dep} = $newstring;

            $cmdhash{$dep} = @wildcardcmdarr;
            #print "@wildcardcmdarr\n";
            #print "$dephashnonsplit{$dep}\n";
        }
    }
}


sub mtime ($) {
   my ($filename) = @_;
   my @stat = stat $filename;
   return @stat ? $stat[9] : undef;
}

sub process {
    my $currtar = $_[0];
    #print "@{$cmdhash{$currtar}} \n";
    #print "current target: $currtar ";
    if ($istargetcomplete{$currtar} == 0) {
        my @deps;
        if (defined($dephashnonsplit{$currtar})) {
            my $depstr = $dephashnonsplit{$currtar};
            $depstr =~ s/: //;
            @deps = split ' ', $depstr;
        }

        #rint "deps: @deps\n";
        #https://stackoverflow.com/questions/2601027/how-can-i-check-if-a-file-exists-in-perl
        if (-e $currtar) { # if its a file
            foreach my $singledep (@deps) {
                handlewildcard $singledep;
                # check to see if its a target and if it is then process
                my $isTar = 0;
                foreach my $tar (@alltargets) {
                    if ($singledep eq $tar) {
                        $isTar = 1;
                    }
                }
                if ($isTar) {
                    process($singledep);
                }
                # target is obsolete
                elsif ((-e $singledep) && (mtime($currtar) < mtime($singledep))) {
                    my @currcmdarr;
                    my $length;
                    if (defined $cmdhash{$currtar}) {
                        @currcmdarr = @{$cmdhash{$currtar}};
                        $length = @{$cmdhash{$currtar}};
                    }
                    if ($length > 1) {
                        foreach my $thiscmd (@currcmdarr) {
                            executecmd $thiscmd;                    
                        }
                    }
                    else {
                        my $currcmd = $cmdhashstringed{$currtar};
                        #print "$currcmd\n";
                        executecmd $currcmd;
                    }
                    $somethingdone = 1;
                }
            }
        }
        else { #not a file
            foreach my $singledep (@deps) {
                handlewildcard $singledep;
                my $isTar = 0;
                foreach my $tar (@alltargets) {
                    if ($singledep eq $tar) {
                        $isTar = 1;
                    }
                    #print "$singledep : $tar\n";
                }
                handlewildcard $singledep;
                if ($isTar) {
                    #print "$singledep\n";
                    process($singledep);
                }
            }
            my @currcmdarr;
            my $length = 0;
            if (defined $cmdhash{$currtar}) {
                @currcmdarr = @{$cmdhash{$currtar}};
                $length = @{$cmdhash{$currtar}};
            }
            if ($length > 1) {
                foreach my $thiscmd (@currcmdarr) {
                    executecmd $thiscmd;                    
                }
            }
            else {
                my $currcmd = $cmdhashstringed{$currtar};
                #print "$currcmd\n";
                executecmd $currcmd;
            }
            $somethingdone = 1;
        }
    }
    $istargetcomplete{$currtar} = 1;
}
close $infile;

if (not $target) {
  $target = $alltargets[0];
}
#print "global target: $target\n";
process($target);
if (not $somethingdone) {
  #print "pmake: '$target' is up to date.\n";
}


#if decoding, print hashtable
if ($OPTS{'d'}) {
    print "\n MACRO HASHTABLE\n\n";
    my ($k,$v) = (0,0);
    while ( ($k,$v) = each %macrohash ) {
        print "$k => $v\n";
    }
    print "\n DEP HASHTABLE\n\n";
    for $k ( keys %dephash ) {
    print "$k: @{ $dephash{$k} }\n";
    }
    print "\n End DEP HASHTABLE\n\n";

    print "\n CMD HASHTABLE\n\n";
    for $k ( keys %cmdhash ) {
    print "$k: @{ $cmdhash{$k} }\n";
    }
    print "\n End CMD HASHTABLE\n\n";
    print "TARGETS\n";
    print "\n@alltargets\n";
};
